# -- path setting
train_json_path : '/opt/ml/final-project-level3-cv-04/Data set/annotations/general_11_30.json'
validation_json_path : '/opt/ml/final-project-level3-cv-04/Data set/annotations/general_31_45.json'
image_path : '/opt/ml/final-project-level3-cv-04/Data set/real data/general'
save_path : './saved/unet_3p'

# -- hyperparameter
epochs : 1000
batch_size : 4
lr : 0.0001

# -- validation
validate : True
eval_interval : 50

